project:
  type: website

website:
  title: "Actionable Analytics"
  reader-mode: true
  cookie-consent: false
  page-footer:
      background: darkblue
      border: true
      left: "Copyright @2023, Eddwin Cheteni"
      right:
        - icon: github
          href: https://github.com/eddychetz/
        - icon: facebook
          href: https://facebook.com/
      center:
        - text: "About"
          href: about.qmd
        - text: "License"
          href: license.qmd
        - text: "Trademark"
          href: trademark.qmd

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:services
      - sidebar:blog
      - sidebar:projects
      - sidebar:about

  sidebar:
    - id: home
      title: "Home"
      style: "docked"
      background: dark
      contents:
        - index.qmd
    - id: services
      title: "Services"
      style: "docked"
      background: dark
      contents:
        - services.qmd
    - id: blog
      title: "Blog"
      style: "docked"
      background: dark
      contents:
        - text: "My Blog Posts"
          href: https://actionable-blog-posts.netlify.app
    - id: projects
      title: "Projects"
      style: "docked"
      background: dark
      contents:
        - projects.qmd
    - id: about
      title: "More"
      style: "docked"
      background: dark
      contents:
        - about.qmd
        - contact.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

