project:
  type: website

website:
  title: "Actionable Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

