project:
  type: website

website:
  title: "Actionable Analytics"
  reader-mode: true
  cookie-consent: false
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:services
      - sidebar:blog
      - sidebar:projects
      - text: "About"
        file: about.qmd
      - text: "Contact"
        file: contact.qmd


  sidebar:
    - id: services
      title: "Services"
      style: "docked"
      background: light
      contents:
        - actionable-talks.qmd
        - actionable-learn.qmd
    - id: blog
      title: "Blog"
      style: "docked"
      background: dark
      contents:
        - r-blog.qmd
        - py-blog.qmd
    - id: projects
      title: "Projects"
      style: "docked"
      background: light
      contents:
        - time-series.qmd
        - cust-segmentation.qmd
        - price-prediction.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true

page-footer:
    background: light
    border: true
    left: "Copyright 2023, Eddwin Cheteni"
    right:
      - icon: github
        href: https://github.com/eddychetz/
      - icon: facebook
        href: https://facebook.com/
